name: Upload site to staging server for tests

on:
#  push:
  workflow_dispatch:
env:
  HOME: /home/usrgit

jobs:
  job_1:
    runs-on: self-hosted
    steps:
      - name: git checkout last version
        uses: actions/checkout@v4
        with:
          repository: AlexanderBend/5550055
          
      - name: ls
        run: ls -l
        
      - name: tar and clear old files
        run: |
          tar -cfv ${{ env.HOME }}/site_old_$(date '+%Y-%m-%d').tar /var/www/555 && \
          sudo rm -rf /var/www/555
          
      - name: test ls
        run: |
          ls -l
